### ISSUE TITLE
Bulk insert using postgreSQL

### ISSUE THREAD

**Issue by venkatbachan09** [robconery/dox#2]
Hi Rob,
i can able to loop over all the documents and insert but performance prospective we need to insert at a time to all documents, 
i read many places that we can use COPY, but how can we use it.
how can we insert bulk of documents into details jsonb and if we insert then how the primary key generate automatically, please help me.

Thanks.

**Comment by robconery** [comment]
I want to help but this isn’t an issue I can do something about. Emailed would work better.

I can’t do much without specifics and how something fails (or not).
