### ISSUE TITLE
Why the creation of a lookup column vs an index?

### ISSUE THREAD

**Issue by agad** [robconery/dox#3]
Wouldn't an index on the specific parts of the JSONB structure be more efficient for what you are looking for?  ie:

`
CREATE INDEX idx_jsonpart ON jsonTbl(cast(body->>'intvalue' AS INT));
`

No trigger maintenance and it would accomplish what I think you are attempting to accomplish via the lookup.  Or am I missing the purpose behind the lookups?

**Comment by robconery** [comment]
The lookup is mostly me just messing around with starts and end with resolution. I don't *think* you can index a key like that; it only uses `contains` or `exists`. What I want is for you to be able to query on something like `company_name` starting with "St", for instance without executing a full table scan. Right now you can't do that, so I thought "this might work ... let's try it".
